---
  - name: Added Official Nginx repo
    copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo owner=root group=root

  - name: Install nginx
    yum: name=nginx state=latest
    notify: Restart Nginx

  - name: Create nginx.conf file
    copy: src=nginx.conf dest=/etc/nginx/ owner=root group=root mode=644
    notify: Reload Nginx
