---
  - name: git clone webapp
    git:  repo={{ app_git_link }} dest={{ app_directory }} accept_hostkey=yes
    sudo_user: "{{ user }}"

  - name: Install deps via NPM
    npm: path={{ app_directory }}

  - name: Run Gulp
    shell: gulp chdir={{ app_directory }}
